---
- name: Manage users and groups with external variables
  hosts: n01659360-c-vm1.canadacentral.cloudapp.azure.com
  become: yes
  vars_files:
    - ~/automation/ansible/vars/userinfo.yml
  tasks:
    - name: Create group group100
      group:
        name: "{{ grouplist1 }}"
        state: present

    - name: Create group group200
      group:
        name: "{{ grouplist2 }}"
        state: present

    - name: Create user user100 with UID 2800 and supplementary group membership to group100
      user:
        name: "{{ userlist1 }}"
        uid: "{{ uid1 }}"
        groups: "{{ grouplist1 }}"
        append: yes
        state: present

    - name: Create user user200 with UID 2900, shell /bin/bash, home directory /home/user200, and supplementary group membership to group200
      user:
        name: "{{ userlist2 }}"
        uid: "{{ uid2 }}"
        shell: /bin/bash
        home: "/home/{{ userlist2 }}"
        groups: "{{ grouplist2 }}"
        append: yes
        state: present
