---
- name: Copy issue file and set permissions
  hosts: n01659360-c-vm1.canadacentral.cloudapp.azure.com
  become: yes
  tasks:
    - name: Copy /etc/issue file
      copy:
        src: /etc/issue
        dest: /etc/issue
        owner: user4000
        group: cloudadmins
        mode: '0444'

- name: Change timezone
  hosts: linux
  become: yes
  tasks:
    - name: Set timezone to America/Edmonton
      timezone:
        name: America/Edmonton
